local lsp = {
		LspDiagnosticsDefaultError = {fg = C.error_red, },
		LspDiagnosticsDefaultWarning = {fg = C.warning_orange, },
		LspDiagnosticsDefaultInformation = {fg = C.info_yellow, },
		LspDiagnosticsDefaultHint = {fg = C.hint_blue, },
		LspDiagnosticsVirtualTextError = {fg = C.error_red, },
		LspDiagnosticsVirtualTextWarning = {fg = C.warning_orange, },
		LspDiagnosticsVirtualTextInformation = {fg = C.info_yellow, },
		LspDiagnosticsVirtualTextHint = {fg = C.hint_blue, },
		LspDiagnosticsFloatingError = {fg = C.error_red, },
		LspDiagnosticsFloatingWarning = {fg = C.warning_orange, },
		LspDiagnosticsFloatingInformation = {fg = C.info_yellow, },
		LspDiagnosticsFloatingHint = {fg = C.hint_blue, },
		LspDiagnosticsSignError = {fg = C.error_red, },
		LspDiagnosticsSignWarning = {fg = C.warning_orange, },
		LspDiagnosticsSignInformation = {fg = C.info_yellow, },
		LspDiagnosticsSignHint = {fg = C.hint_blue, },
		LspDiagnosticsError = {fg = C.error_red, },
		LspDiagnosticsWarning = {fg = C.warning_orange, },
		LspDiagnosticsInformation = {fg = C.info_yellow, },
		LspDiagnosticsHint = {fg = C.hint_blue, },
		LspDiagnosticsUnderlineError = {fg = C.error_red, },
		LspDiagnosticsUnderlineWarning = {fg = C.warning_orange, },
		LspDiagnosticsUnderlineInformation = {fg = C.info_yellow, },
		LspDiagnosticsUnderlineHint = {fg = C.hint_blue, },
		QuickScopePrimary = {fg = C.cyan_test, style = "underline", },
		QuickScopeSecondary = {fg = C.purple_test, style = "underline", },
		TelescopeSelection = {fg = C.cyan, },
		TelescopeMatching = {fg = C.red, style = "bold", },
		TelescopeBorder = {fg = C.hint_blue, bg = C.alt_bg, },
		NvimTreeFolderIcon = {fg = C.blue, },
		NvimTreeIndentMarker = {fg = C.grey, },
		NvimTreeNormal = {fg = C.light_grey, bg = C.alt_bg, },
		NvimTreeFolderName = {fg = C.blue, },
		NvimTreeOpenedFolderName = {fg = C.cyan, style = "italic", },
		NvimTreeImageFile = {fg = C.purple, },
		NvimTreeSpecialFile = {fg = C.purple, },
		NvimTreeGitStaged = {fg = C.sign_add, },
		NvimTreeGitNew = {fg = C.sign_add, },
		NvimTreeGitDirty = {fg = C.sign_add, },
		NvimTreeGitDeleted = {fg = C.sign_delete, },
		NvimTreeGitMerge = {fg = C.sign_change, },
		NvimTreeGitRenamed = {fg = C.sign_change, },
		NvimTreeSymlink = {fg = C.cyan, },
		NvimTreeRootFolder = {fg = C.fg, style = "bold", },
		NvimTreeExecFile = {fg = C.light_green, },
		BufferCurrent = {fg = C.fg, bg = C.bg, },
		BufferCurrentIndex = {fg = C.cyan, bg = C.bg, },
		BufferCurrentMod = {fg = C.info_yellow, bg = C.bg, },
		BufferCurrentSign = {fg = C.cyan, bg = C.bg, },
		BufferCurrentTarget = {fg = C.red, bg = C.bg, style = "bold", },
		BufferVisible = {fg = C.fg, bg = C.bg, },
		BufferVisibleIndex = {fg = C.fg, bg = C.bg, },
		BufferVisibleMod = {fg = C.info_yellow, bg = C.bg, },
		BufferVisibleSign = {fg = C.warning_orange, bg = C.bg, },
		BufferVisibleTarget = {fg = C.red, bg = C.bg, style = "bold", },
		BufferInactive = {fg = C.grey, bg = C.alt_bg, },
		BufferInactiveIndex = {fg = C.grey, bg = C.alt_bg, },
		BufferInactiveMod = {fg = C.info_yellow, bg = C.alt_bg, },
		BufferInactiveSign = {fg = C.grey, bg = C.alt_bg, },
		BufferInactiveTarget = {fg = C.red, bg = C.alt_bg, style = "bold", },
		StatusLine = {fg = C.grey, bg = C.alt_bg, },
		StatusLineNC = {fg = C.grey, bg = C.alt_bg, },
		StatusLineSeparator = {fg = C.grey, bg = C.alt_bg, },
		StatusLineTerm = {fg = C.grey, bg = C.alt_bg, },
		StatusLineTermNC = {fg = C.grey, bg = C.alt_bg, },
		CodiVirtualText = {fg = C.pale_purple, },
		IndentBlanklineContextChar = {fg = C.accent, },
		DashboardHeader = {fg = C.blue, },
		DashboardCenter = {fg = C.purple, },
		DashboardFooter = {fg = C.cyan, },
		CompeDocumentation = {bg = C.alt_bg, },
		DiffViewNormal = {fg = C.grey, bg = C.alt_bg, },
		DiffviewStatusAdded = {fg = C.SignAdd, },
		DiffviewStatusModified = {fg = C.SignChange, },
		DiffviewStatusRenamed = {fg = C.SignChange, },
		DiffviewStatusDeleted = {fg = C.SignDelete, },
		DiffviewFilePanelInsertion = {fg = C.SignAdd, },
		DiffviewFilePanelDeletion = {fg = C.SignDelete, },
		DiffviewVertSplit = {fg = C.grey, bg = C.bg, },
		diffAdded = {fg = C.sign_add, },
		diffRemoved = {fg = C.sign_delete, },
		diffFileId = {fg = C.blue, style = "bold,reverse", },
		diffFile = {fg = C.alt_bg, },
		diffNewFile = {fg = C.green, },
		diffOldFile = {fg = C.red, },
		debugPc = {bg = C.cyan, },
		debugBreakpoint = {fg = C.red, style = "reverse", },
}

return lsp