local treesitter = {
		TSComment = {fg = C.Comment, },
		TSAnnotation = {fg = C.purple, },
		TSAttribute = {fg = C.cyan, },
		TSConstructor = {fg = C.Type, },
		TSType = {fg = C.Type, },
		TSTypeBuiltin = {fg = C.Type, },
		TSConditional = {fg = C.Conditional, },
		TSException = {fg = C.Exception, },
		TSInclude = {fg = C.Exception, },
		TSKeyword = {fg = C.Keyword, },
		TSKeywordFunction = {fg = C.Keyword, },
		TSLabel = {fg = C.Label, },
		TSNamespace = {fg = C.Keyword, },
		TSRepeat = {fg = C.Repeat, },
		TSConstant = {fg = C.Constant, },
		TSConstBuiltin = {fg = C.Constant, },
		TSFloat = {fg = C.Float, },
		TSNumber = {fg = C.Number, },
		TSBoolean = {fg = C.Boolean, },
		TSCharacter = {fg = C.Character, },
		TSError = {fg = C.Error, },
		TSFunction = {fg = C.Function, },
		TSFuncBuiltin = {fg = C.Function, },
		TSMethod = {fg = C.Function, },
		TSConstMacro = {fg = C.Macro, },
		TSFuncMacro = {fg = C.Macro, },
		TSVariable = {fg = C.Variable, },
		TSVariableBuiltin = {fg = C.cyan, },
		TSProperty = {fg = C.cyan, },
		TSOperator = {fg = C.Operator, },
		TSField = {fg = C.Variable, },
		TSParameter = {fg = C.Variable, },
		TSParameterReference = {fg = C.Variable, },
		TSSymbol = {fg = C.Identifier, },
		TSText = {fg = C.fg, },
		TSPunctDelimiter = {fg = C.Delimiter, },
		TSTagDelimiter = {fg = C.Delimiter, },
		TSPunctBracket = {fg = C.Delimiter, },
		TSPunctSpecial = {fg = C.Delimiter, },
		TSString = {fg = C.String, },
		TSStringRegex = {fg = C.String, },
		TSStringEscape = {fg = C.Character, },
		TSWarning = {fg = C.Todo, },
		TSTag = {fg = C.Tag, },
		TSEmphasis = {style = "italic", },
		TSUnderline = {style = "underline", },
		TSTitle = {fg = C.Title, },
		TSLiteral = {fg = C.String, },
		TSURI = {fg = C.cyan, style = "underline", },
		TSKeywordOperator = {fg = C.blue, },
		TSStructure = {fg = C.purple_test, },
		TSStrong = {fg = C.yellow, },
		TSQueryLinterError = {fg = C.warning_orange, },
}

return treesitter