local Treesitter = {
		TSComment = {fg = C.accent, style = "italic", },
		TSError = {fg = C.error_red, },
		TSPunctDelimiter = {fg = C.white, },
		TSPunctBracket = {fg = C.white, },
		TSPunctSpecial = {fg = C.white, },
		TSConstant = {fg = C.yellow, },
		TSConstBuiltin = {fg = C.blue, },
		TSConstMacro = {fg = C.cyan, },
		TSStringRegex = {fg = C.green, },
		TSString = {fg = C.green, },
		TSStringEscape = {fg = C.yellow, },
		TSCharacter = {fg = C.orange, },
		TSNumber = {fg = C.red, },
		TSBoolean = {fg = C.orange, },
		TSFloat = {fg = C.red, },
		TSAnnotation = {fg = C.yellow, },
		TSAttribute = {fg = C.cyan, },
		TSNamespace = {fg = C.cyan, },
		TSFuncBuiltin = {fg = C.yellow, },
		TSFunction = {fg = C.yellow, },
		TSFuncMacro = {fg = C.yellow, },
		TSParameter = {fg = C.white, },
		TSParameterReference = {fg = C.white, },
		TSMethod = {fg = C.yellow, },
		TSField = {fg = C.white, },
		TSProperty = {fg = C.cyan, },
		TSConstructor = {fg = C.purple, },
		TSConditional = {fg = C.grey_blue, },
		TSRepeat = {fg = C.blue, },
		TSLabel = {fg = C.cyan, },
		TSKeyword = {fg = C.blue, },
		TSKeywordFunction = {fg = C.grey_blue, },
		TSKeywordOperator = {fg = C.blue, },
		TSOperator = {fg = C.grey_blue, },
		TSException = {fg = C.blue, },
		TSType = {fg = C.purple, },
		TSTypeBuiltin = {fg = C.purple, },
		TSStructure = {fg = "#FF00FF", },
		TSInclude = {fg = C.blue, },
		TSVariable = {fg = C.white, },
		TSVariableBuiltin = {fg = C.white, },
		TSText = {fg = C.fg, },
		TSStrong = {fg = C.yellow, },
		TSEmphasis = {fg = C.purple, },
		TSUnderline = {fg = C.red, },
		TSTitle = {fg = C.fg, },
		TSLiteral = {fg = C.grey, },
		TSURI = {style = "underline", },
		TSTag = {fg = C.blue, },
		TSTagDelimiter = {fg = C.accent, },
		TSQueryLinterError = {fg = C.warning_orange, },
		htmlArg = {fg = C.yellow, },
		htmlBold = {fg = C.yellow, style = "bold", },
		htmlEndTag = {fg = C.white, },
		htmlH1 = {fg = C.blue, },
		htmlH2 = {fg = C.blue, },
		htmlH3 = {fg = C.blue, },
		htmlH4 = {fg = C.blue, },
		htmlH5 = {fg = C.blue, },
		htmlH6 = {fg = C.blue, },
		htmlItalic = {fg = C.purple, style = "italic", },
		htmlLink = {fg = C.cyan, style = "underline", },
		htmlSpecialChar = {fg = C.yellow, },
		htmlSpecialTagName = {fg = C.blue, },
		htmlTag = {fg = C.white, },
		htmlTagN = {fg = C.blue, },
		htmlTagName = {fg = C.blue, },
		htmlTitle = {fg = C.white, },
		markdownBlockquote = {fg = C.accent, },
		markdownBold = {fg = C.yellow, style = "bold", },
		markdownCode = {fg = C.green, },
		markdownCodeBlock = {fg = C.green, },
		markdownCodeDelimiter = {fg = C.green, },
		markdownH1 = {fg = C.blue, },
		markdownH2 = {fg = C.blue, },
		markdownH3 = {fg = C.blue, },
		markdownH4 = {fg = C.blue, },
		markdownH5 = {fg = C.blue, },
		markdownH6 = {fg = C.blue, },
		markdownHeadingDelimiter = {fg = C.red, },
		markdownHeadingRule = {fg = C.accent, },
		markdownId = {fg = C.purple, },
		markdownIdDeclaration = {fg = C.blue, },
		markdownIdDelimiter = {fg = C.purple, },
		markdownItalic = {fg = C.purple, style = "italic", },
		markdownLinkDelimiter = {fg = C.purple, },
		markdownLinkText = {fg = C.blue, },
		markdownListMarker = {fg = C.red, },
		markdownOrderedListMarker = {fg = C.red, },
		markdownRule = {fg = C.accent, },
		markdownUrl = {fg = C.cyan, style = "underline", },
		CocExplorerIndentLine = {fg = C.accent, },
		CocExplorerBufferRoot = {fg = C.cyan, },
		CocExplorerFileRoot = {fg = C.cyan, },
		CocExplorerBufferFullPath = {fg = C.accent, },
		CocExplorerFileFullPath = {fg = C.accent, },
		CocExplorerBufferReadonly = {fg = C.purple, },
		CocExplorerBufferModified = {fg = C.purple, },
		CocExplorerBufferNameVisible = {fg = C.orange, },
		CocExplorerFileReadonly = {fg = C.purple, },
		CocExplorerFileModified = {fg = C.purple, },
		CocExplorerFileHidden = {fg = C.accent, },
		CocExplorerHelpLine = {fg = C.purple, },
		EasyMotionTarget = {fg = C.error_red, style = "bold", },
		EasyMotionTarget2First = {fg = C.error_red, style = "bold", },
		EasyMotionTarget2Second = {fg = C.error_red, style = "bold", },
		StartifyNumber = {fg = C.red, },
		StartifySelect = {fg = C.green, },
		StartifyBracket = {fg = C.blue, },
		StartifySpecial = {fg = C.cyan, },
		StartifyVar = {fg = C.blue, },
		StartifyPath = {fg = C.blue, },
		StartifyFile = {fg = C.cyan, },
		StartifySlash = {fg = C.blue, },
		StartifyHeader = {fg = C.cyan, },
		StartifySection = {fg = C.purple, },
		StartifyFooter = {fg = C.green, },
		WhichKey = {fg = C.purple, },
		WhichKeySeperator = {fg = C.green, },
		WhichKeyGroup = {fg = C.hint_blue, },
		WhichKeyDesc = {fg = C.blue, },
		diffAdded = {fg = C.green, },
		diffRemoved = {fg = C.red, },
		diffFileId = {fg = C.blue, style = "bold,reverse", },
		diffFile = {fg = C.alt_bg, },
		diffNewFile = {fg = C.green, },
		diffOldFile = {fg = C.red, },
		debugPc = {bg = C.cyan, },
		debugBreakpoint = {fg = C.red, style = "reverse", },
		GitSignsAdd = {fg = C.sign_add, },
		GitSignsChange = {fg = C.sign_change, },
		GitSignsDelete = {fg = C.sign_delete, },
		LspDiagnosticsUnderlineHint = {fg = C.grey, },
		LspDiagnosticsSignError = {fg = C.error_red, },
		LspDiagnosticsSignWarning = {fg = C.warning_orange, },
		LspDiagnosticsSignInformation = {fg = C.info_yellow, },
		LspDiagnosticsSignHint = {fg = C.hint_blue, },
		LspDiagnosticsVirtualTextError = {fg = C.error_red, },
		LspDiagnosticsVirtualTextWarning = {fg = C.warning_orange, },
		LspDiagnosticsVirtualTextInformation = {fg = C.info_yellow, },
		LspDiagnosticsVirtualTextHint = {fg = C.hint_blue, },
		QuickScopePrimary = {fg = "#00C7DF", style = "underline", },
		QuickScopeSecondary = {fg = "#eF5F70", style = "underline", },
		MatchWord = {style = "underline", },
		MatchParen = {style = "underline", },
		MatchWordCur = {style = "underline", },
		MatchParenCur = {style = "underline", },
		NvimTreeImageFile = {fg = C.purple, },
		NvimTreeGitDirty = {fg = C.sign_add, },
		NvimTreeGitDeleted = {fg = C.sign_add, },
		NvimTreeGitStaged = {fg = C.sign_add, },
		NvimTreeGitMerge = {fg = C.sign_add, },
		NvimTreeGitRenamed = {fg = C.sign_add, },
		NvimTreeGitNew = {fg = C.sign_add, },
		NvimTreeIndentMarker = {fg = C.accent, },
		NvimTreeSymlink = {fg = C.cyan, },
		NvimTreeFolderIcon = {fg = C.blue, },
		NvimTreeRootFolder = {fg = C.fg, style = "bold", },
		NvimTreeExecFile = {fg = C.light_green, },
		NvimTreeSpecialFile = {fg = C.info_yellow, },
		NvimTreeLspDiagnostics = {fg = C.warning_orange, },
		BufferCurrent = {fg = C.fg, bg = C.bg, },
		BufferCurrentIndex = {fg = C.blue, bg = C.bg, },
		BufferCurrentMod = {fg = C.fg, bg = C.bg, },
		BufferCurrentSign = {fg = C.blue, bg = C.bg, },
		BufferCurrentTarget = {fg = C.red, bg = C.bg, style = "bold", },
		BufferVisible = {fg = C.fg, bg = C.bg, },
		BufferVisibleIndex = {fg = C.fg, bg = C.bg, },
		BufferVisibleMod = {fg = C.fg, bg = C.bg, },
		BufferVisibleSign = {fg = C.fg, bg = C.bg, },
		BufferVisibleTarget = {fg = C.red, bg = C.bg, style = "bold", },
		BufferInactive = {fg = C.accent, bg = C.alt_bg, },
		BufferInactiveIndex = {fg = C.accent, bg = C.alt_bg, },
		BufferInactiveMod = {fg = C.accent, bg = C.alt_bg, },
		BufferInactiveSign = {fg = C.accent, bg = C.alt_bg, },
		BufferInactiveTarget = {fg = C.red, bg = C.alt_bg, style = "bold", },
		CodiVirtualText = {fg = C.pale_purple, },
		IndentBlanklineContextChar = {fg = C.accent, },
		DashboardHeader = {fg = C.cyan, },
		DashboardCenter = {fg = C.orange, },
		DashboardFooter = {fg = C.cyan, },
		WhichKeyFloat = {fg = C.bg, },
		VimwikiHeader1 = {fg = C.orange, style = "bold", },
		VimwikiHeader2 = {fg = C.green, style = "bold", },
		VimwikiHeader3 = {fg = C.blue, style = "bold", },
		VimwikiHeader4 = {fg = C.cyan, style = "bold", },
		VimwikiHeader5 = {fg = C.yellow, style = "bold", },
		VimwikiHeader6 = {fg = C.purple, style = "bold", },
		VimwikiLink = {fg = C.hint_blue, },
		VimwikiHeaderChar = {fg = C.accent, },
		VimwikiHR = {fg = C.yellow, },
		VimwikiList = {fg = C.orange, },
		VimwikiTag = {fg = C.orange, },
		VimwikiMarkers = {fg = C.accent, },
}

return Treesitter